baseURL = "https://onestla.tech/"
defaultContentLanguage = "fr"
languageCode = "fr-fr"
title = "✊ onestla.tech"
theme = "hyde-hyde"
sectionPagesMenu = "main"

[Params]
  socialShare = false
  organizationName = "onestla.tech"
  favicon = "avatar.png"
  logo = "avatar.png"

  [markup.goldmark.renderer]
  unsafe = true
