baseURL = "https://onestla.tech/"
defaultContentLanguage = "fr"
languageCode = "fr-fr"
title = "✊ onestla.tech"
theme = "beautifulhugo"
sectionPagesMenu = "main"

[Params]
  socialShare = false
  organizationName = "onestla.tech"
  favicon = "avatar.png"
  logo = "avatar.png"

  [markup.goldmark.renderer]
  unsafe = true

[menu]
[[menu.main]]
  identifier = 'adhesion'
  title = 'Adhérer'
  url = 'https://opencollective.com/onestlatech'
  weight = 3
[[menu.main]]
  identifier = 'conference'
  title = 'Conférence'
  url = 'https://conf.onestla.tech'
  weight = 3
